.TH "argparse::arguments" 3 "Mon Jun 6 2022" "fsop - FileSystem OPerations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
argparse::arguments \- \fBArgument\fP variables for use as named arguments\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBdefaults\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtypes::Name::Argument\fP \fBname\fP"
.br
.ti -1c
.RI "\fBtypes::Help::Argument\fP \fBhelp\fP"
.br
.ti -1c
.RI "\fBtypes::Alias::Argument\fP \fBalias\fP"
.br
.ti -1c
.RI "\fBtypes::Destination::Argument\fP \fBdest\fP"
.br
.ti -1c
.RI "\fBtypes::DefaultValue::Argument\fP \fBdefault_value\fP"
.br
.ti -1c
.RI "\fBtypes::Arity::Argument\fP \fBarity\fP"
.br
.ti -1c
.RI "\fBtypes::Choices::Argument\fP \fBchoices\fP"
.br
.ti -1c
.RI "\fBtypes::Transform::Argument\fP \fBtransform\fP"
.br
.ti -1c
.RI "\fBtypes::Required::Argument\fP \fBrequired\fP"
.br
.ti -1c
.RI "\fBtypes::Negated::Argument\fP \fBnegated\fP"
.br
.ti -1c
.RI "\fBtypes::Description::Argument\fP \fBdescription\fP"
.br
.ti -1c
.RI "\fBtypes::Epilog::Argument\fP \fBepilog\fP"
.br
.ti -1c
.RI "\fBtypes::OutputStream::Argument\fP \fBoutput_stream\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBArgument\fP variables for use as named arguments\&. 
.SH "Variable Documentation"
.PP 
.SS "\fBtypes::Alias::Argument\fP argparse::arguments::alias\fC [inline]\fP"
Alias(es) for the argument\&. 
.SS "\fBtypes::Arity::Argument\fP argparse::arguments::arity\fC [inline]\fP"
Arity for the argument (number of values to store)\&. 
.SS "\fBtypes::Choices::Argument\fP argparse::arguments::choices\fC [inline]\fP"
Domain of possible choices for the argument\&. 
.SS "\fBtypes::DefaultValue::Argument\fP argparse::arguments::default_value\fC [inline]\fP"
Default value for the argument\&. 
.SS "\fBtypes::Description::Argument\fP argparse::arguments::description\fC [inline]\fP"
Text to display before the argument help\&. 
.SS "\fBtypes::Destination::Argument\fP argparse::arguments::dest\fC [inline]\fP"
Destination name for the argument in the parsed table\&. 
.SS "\fBtypes::Epilog::Argument\fP argparse::arguments::epilog\fC [inline]\fP"
Text to display after the argument help\&. 
.SS "\fBtypes::Help::Argument\fP argparse::arguments::help\fC [inline]\fP"
Help description for argument\&. 
.SS "\fBtypes::Name::Argument\fP argparse::arguments::name\fC [inline]\fP"
Name to display\&. 
.SS "\fBtypes::Negated::Argument\fP argparse::arguments::negated\fC [inline]\fP"
Whether to treat flag presence as falsy\&. 
.SS "\fBtypes::OutputStream::Argument\fP argparse::arguments::output_stream\fC [inline]\fP"
Stream to display help and usage information in\&. 
.SS "\fBtypes::Required::Argument\fP argparse::arguments::required\fC [inline]\fP"
Whether the argument is to be marked as required\&. 
.SS "\fBtypes::Transform::Argument\fP argparse::arguments::transform\fC [inline]\fP"
Transformation function to apply over argument values\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for fsop - FileSystem OPerations from the source code\&.
