.TH "include/argparse.hpp" 3 "Mon Jun 6 2022" "fsop - FileSystem OPerations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/argparse.hpp \- Defines a module for parsing command-line arguments\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'argparse/common\&.hpp'\fP
.br
\fC#include 'argparse/arguments/argument\&.hpp'\fP
.br
\fC#include 'argparse/arguments/switch\&.hpp'\fP
.br
\fC#include 'argparse/arguments/optional\&.hpp'\fP
.br
\fC#include 'argparse/arguments/positional\&.hpp'\fP
.br
\fC#include 'argparse/parser\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
Defines a module for parsing command-line arguments\&. 


.PP
\fBAuthor\fP
.RS 4
Kinshuk Vasisht (kinshuk.mcs21@cs.du.ac.in, RN: 19) 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2022-05-28
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for fsop - FileSystem OPerations from the source code\&.
