.TH "include/argparse/arguments/argument.hpp" 3 "Mon Jun 6 2022" "fsop - FileSystem OPerations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/argparse/arguments/argument.hpp \- Defines the base class for arguments, which hold argument description and parsing information\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdexcept>\fP
.br
\fC#include '\&.\&./common\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBargparse::Argument\fP"
.br
.RI "Represents a base type to store argument description and parsing information\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBargparse\fP"
.br
.RI "Exposes components for parsing command-line arguments\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines the base class for arguments, which hold argument description and parsing information\&. 


.PP
\fBAuthor\fP
.RS 4
Kinshuk Vasisht (kinshuk.mcs21@cs.du.ac.in, RN: 19) 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2022-05-28
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for fsop - FileSystem OPerations from the source code\&.
