.TH "src/fsop/create.cpp" 3 "Mon Jun 6 2022" "fsop - FileSystem OPerations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fsop/create.cpp \- Source file implementing the functions defined in \fBfsop/create\&.hpp\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'fsop/create\&.hpp'\fP
.br
\fC#include <cerrno>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <system_error>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Source file implementing the functions defined in \fBfsop/create\&.hpp\fP\&. 


.PP
\fBAuthor\fP
.RS 4
Kinshuk Vasisht (kinshuk.mcs21@cs.du.ac.in, RN: 19) 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2022-05-30
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for fsop - FileSystem OPerations from the source code\&.
