.TH "src/fsop/open.cpp" 3 "Sat Jun 18 2022" "fsop - FileSystem OPerations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fsop/open.cpp \- Source file for implementation of static functions for opening files and pipes defined in \fBfsop/file\&.hpp\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'fsop/file\&.hpp'\fP
.br
\fC#include <cerrno>\fP
.br
\fC#include <system_error>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Source file for implementation of static functions for opening files and pipes defined in \fBfsop/file\&.hpp\fP\&. 


.PP
\fBAuthor\fP
.RS 4
Kinshuk Vasisht (kinshuk.mcs21@cs.du.ac.in, RN: 19) 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2022-05-28
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for fsop - FileSystem OPerations from the source code\&.
