.TH "src/fsop_cli/pipe_io.cpp" 3 "Sat Jun 18 2022" "fsop - FileSystem OPerations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fsop_cli/pipe_io.cpp \- Source file containing implementation of the pipe_io function declared in '\fBfsop_cli\&.hpp\fP'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'fsop_cli\&.hpp'\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include 'fsop/file\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
Source file containing implementation of the pipe_io function declared in '\fBfsop_cli\&.hpp\fP'\&. 


.PP
\fBAuthor\fP
.RS 4
Kinshuk Vasisht (kinshuk.mcs21@cs.du.ac.in, RN: 19) 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2022-06-05
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for fsop - FileSystem OPerations from the source code\&.
