.TH "argparse::arguments::defaults" 3 "Tue Jun 7 2022" "fsop - FileSystem OPerations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
argparse::arguments::defaults
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr auto \fBdefault_name\fP = \fBtypes::Name\fP('')"
.br
.ti -1c
.RI "constexpr auto \fBdefault_help\fP = \fBtypes::Help\fP('')"
.br
.ti -1c
.RI "constexpr auto \fBdefault_alias\fP = \fBtypes::Alias\fP('')"
.br
.ti -1c
.RI "constexpr auto \fBdefault_dest\fP = \fBtypes::Destination\fP('')"
.br
.ti -1c
.RI "constexpr auto \fBdefault_arity\fP = \fBtypes::Arity\fP(1)"
.br
.ti -1c
.RI "constexpr auto \fBdefault_negated\fP = \fBtypes::Negated\fP(false)"
.br
.ti -1c
.RI "constexpr auto \fBdefault_description\fP = \fBtypes::Description\fP('')"
.br
.ti -1c
.RI "constexpr auto \fBdefault_epilog\fP = \fBtypes::Epilog\fP('')"
.br
.ti -1c
.RI "auto \fBdefault_transform\fP = \fBtypes::Transform\fP(std::nullopt)"
.br
.ti -1c
.RI "auto \fBdefault_choices\fP = \fBtypes::Choices\fP(std::nullopt)"
.br
.ti -1c
.RI "auto \fBdefault_value\fP = \fBtypes::DefaultValue\fP(std::nullopt)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Default values for arguments\&. 
.SH "Variable Documentation"
.PP 
.SS "constexpr auto argparse::arguments::defaults::default_alias = \fBtypes::Alias\fP('')\fC [inline]\fP, \fC [constexpr]\fP"
Default value for the alias argument\&. 
.SS "constexpr auto argparse::arguments::defaults::default_arity = \fBtypes::Arity\fP(1)\fC [inline]\fP, \fC [constexpr]\fP"
Default value for the arity argument\&. 
.SS "auto argparse::arguments::defaults::default_choices = \fBtypes::Choices\fP(std::nullopt)\fC [inline]\fP"
Default value for the choices argument\&. 
.SS "constexpr auto argparse::arguments::defaults::default_description = \fBtypes::Description\fP('')\fC [inline]\fP, \fC [constexpr]\fP"
Default value for the description argument\&. 
.SS "constexpr auto argparse::arguments::defaults::default_dest = \fBtypes::Destination\fP('')\fC [inline]\fP, \fC [constexpr]\fP"
Default value for the destination argument\&. 
.SS "constexpr auto argparse::arguments::defaults::default_epilog = \fBtypes::Epilog\fP('')\fC [inline]\fP, \fC [constexpr]\fP"
Default value for the epilog argument\&. 
.SS "constexpr auto argparse::arguments::defaults::default_help = \fBtypes::Help\fP('')\fC [inline]\fP, \fC [constexpr]\fP"
Default value for the help argument\&. 
.SS "constexpr auto argparse::arguments::defaults::default_name = \fBtypes::Name\fP('')\fC [inline]\fP, \fC [constexpr]\fP"
Default value for the name argument\&. 
.SS "constexpr auto argparse::arguments::defaults::default_negated = \fBtypes::Negated\fP(false)\fC [inline]\fP, \fC [constexpr]\fP"
Default value for the negated argument\&. 
.SS "auto argparse::arguments::defaults::default_transform = \fBtypes::Transform\fP(std::nullopt)\fC [inline]\fP"
Default value for the transform argument\&. 
.SS "auto argparse::arguments::defaults::default_value = \fBtypes::DefaultValue\fP(std::nullopt)\fC [inline]\fP"
Default value for the default value argument\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for fsop - FileSystem OPerations from the source code\&.
