.TH "include/fsop/file.hpp" 3 "Tue Jun 7 2022" "fsop - FileSystem OPerations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/fsop/file.hpp \- Defines a structure for abstracting I/O operations via system calls\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstddef>\fP
.br
\fC#include <string>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <string_view>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBfsop::File\fP"
.br
.RI "Defines a structure for abstracting I/O operations via system calls\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines a structure for abstracting I/O operations via system calls\&. 


.PP
\fBAuthor\fP
.RS 4
Kinshuk Vasisht (kinshuk.mcs21@cs.du.ac.in, RN: 19) 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2022-06-03
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for fsop - FileSystem OPerations from the source code\&.
