.TH "src/argparse/parser.cpp" 3 "Sat Jun 18 2022" "fsop - FileSystem OPerations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/argparse/parser.cpp \- Source file implementing the methods defined in \fBargparse/parser\&.hpp\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'argparse/parser\&.hpp'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr auto \fBselect_first\fP = [](const auto& x) \-> auto& { return x\&.first; }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Source file implementing the methods defined in \fBargparse/parser\&.hpp\fP\&. 


.PP
\fBAuthor\fP
.RS 4
Kinshuk Vasisht (kinshuk.mcs21@cs.du.ac.in, RN: 19) 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2022-05-30
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "constexpr auto select_first = [](const auto& x) \-> auto& { return x\&.first; }\fC [constexpr]\fP"
Selects the first element of a pair object\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for fsop - FileSystem OPerations from the source code\&.
