.TH "include/argparse/parser.hpp" 3 "Mon Jun 6 2022" "fsop - FileSystem OPerations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/argparse/parser.hpp \- Defines the parser class which performs argument parsing using registered arguments\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'common\&.hpp'\fP
.br
\fC#include 'arguments/argument\&.hpp'\fP
.br
\fC#include 'arguments/switch\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBargparse::SubparserSet\fP"
.br
.RI "Creates an argument type to hold subparsers as a mutually exclusive group\&. "
.ti -1c
.RI "class \fBargparse::Parser\fP"
.br
.RI "Represents an argument parser, which can parse argument values from arbitrary ranges using provided argument objects describing parsing information\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBargparse\fP"
.br
.RI "Exposes components for parsing command-line arguments\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines the parser class which performs argument parsing using registered arguments\&. 


.PP
\fBAuthor\fP
.RS 4
Kinshuk Vasisht (kinshuk.mcs21@cs.du.ac.in, RN: 19) 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2022-05-28
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for fsop - FileSystem OPerations from the source code\&.
