.TH "include/argparse/arguments/switch.hpp" 3 "Sat Jun 18 2022" "fsop - FileSystem OPerations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/argparse/arguments/switch.hpp \- Defines an argument subtype for switch arguments, which may be used to represent flags for boolean or constant values\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'argparse/common\&.hpp'\fP
.br
\fC#include 'argparse/arguments/argument\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBargparse::Switch\fP"
.br
.RI "Represents a switch/flag argument, which has no arity and is used to store a boolean or a constant upon presence or absence\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBargparse\fP"
.br
.RI "Exposes components for parsing command-line arguments\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines an argument subtype for switch arguments, which may be used to represent flags for boolean or constant values\&. 


.PP
\fBAuthor\fP
.RS 4
Kinshuk Vasisht (kinshuk.mcs21@cs.du.ac.in, RN: 19) 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2022-05-28
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for fsop - FileSystem OPerations from the source code\&.
